# Generated by Django 3.2 on 2023-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_confirmationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
