# Generated by Django 3.2 on 2023-12-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='reviews.review', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
