# Generated by Django 3.2 on 2023-12-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20231207_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.review', verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
